version: '3.1'

services:
  db:
    image: postgres
    container_name: spring_webflux_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: